### ISSUE TITLE
Evaluate works in a surprising way when starting from a particular node.

### ISSUE THREAD

**Issue by fiddlerwoaroof** [sharplispers/xpath#12]
If I call `xpath:evaluate` with a particular node, I don't expect the node-set iterator to map through that node's parents.  Currently, if I evaluate the XPath expression `//c` using the first `b` node as context, I get all four `c` nodes back.

```lisp
ICS->CSV> (let* ((xml (cxml:parse 
                       "<a><b><c>0</c></b><b><c>1</c></b><b><c>2</c></b><b><c>3</c></b></a>"
                       (cxml-stp:make-builder)))
                 (el (first (xpath:map-node-set->list 'identity
                                                      (xpath:evaluate "//b" xml)))))
            (xpath:map-node-set->list 'identity
                                      (xpath:evaluate "//c" el)))
(#.(CXML-STP:ELEMENT
    #| :PARENT of type ELEMENT |#
    :CHILDREN '(#.(CXML-STP:TEXT #| :PARENT of type ELEMENT |# :DATA "0"))
    :LOCAL-NAME "c")
 #.(CXML-STP:ELEMENT
    #| :PARENT of type ELEMENT |#
    :CHILDREN '(#.(CXML-STP:TEXT #| :PARENT of type ELEMENT |# :DATA "1"))
    :LOCAL-NAME "c")
 #.(CXML-STP:ELEMENT
    #| :PARENT of type ELEMENT |#
    :CHILDREN '(#.(CXML-STP:TEXT #| :PARENT of type ELEMENT |# :DATA "2"))
    :LOCAL-NAME "c")
 #.(CXML-STP:ELEMENT
    #| :PARENT of type ELEMENT |#
    :CHILDREN '(#.(CXML-STP:TEXT #| :PARENT of type ELEMENT |# :DATA "3"))
    :LOCAL-NAME "c"))
```

**Comment by scymtym** [comment]
Using the document root as the context node seems correct:

> A "//" at the beginning of a path expression is an abbreviation for the initial steps (fn:root(self::node()) treat as document-node())/descendant-or-self::node()/ (however, "//" by itself is not a valid path expression [err:XPST0003].) The effect of these initial steps is to establish an initial node sequence that contains the root of the tree in which the context node is found, plus all nodes descended from this root. This node sequence is used as the input to subsequent steps in the path expression. If the context item is not a node, a type error is raised [err:XPTY0020]. At evaluation time, if the root node above the context node is not a document node, a dynamic error is raised [err:XPDY0050].

From https://www.w3.org/TR/xpath20/#id-path-expressions

**Comment by fiddlerwoaroof** [comment]
Hmm, I guess this is a misunderstanding: I can reproduce it with the browser's XPath implementation too.
