### ISSUE TITLE
Cannot run the first example. `stp` does not exist.

### ISSUE THREAD

**Issue by vindarel** [sharplispers/xpath#9]
After loading `xpath`, I can't run the preparation step out of the box, parsing the XML:

```
(defparameter *document*
	   (cxml:parse "<test a='1' b='2' xmlns:foo='http://foo'>
                          <child>hello world</child>
                          <foo:child>bar</foo:child>
                        </test>"
		       (stp:make-builder)))
```
=> 

    package STP does not exist.

It looks like `cxml-stp` is required.

Or if it isn't, what is an alternative to `(stp:make-builder)` ?

**Comment by luismbo** [comment]
cxml-dom:make-dom-builder is one alternative. What documentation are you referring to?

**Comment by vindarel** [comment]
The official example uses `stp`: https://common-lisp.net/project/plexippus-xpath/examples.html 

`cxml-dom:make-dom-builder` works out of the box, wouldn't it be better in the doc ?
